server:
  port: 8087
  servlet:
    context-path: /quartz
    tomcat:
      uri-encoding: utf-8
      
spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
  # 配置文件
  profiles:
    active: test
  # eureka 注册名称
  application:
    name: rain-quartz
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            # 设置集群检查间隔20s
            clusterCheckinInterval: 2000
            dataSource: quartzDataSource
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 打开集群配置
            isClustered: true
            tablePrefix: QRTZ_
            useProperties: false
          scheduler:
            instanceId: AUTO
            instanceName: clusteredScheduler
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rao.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# 通用 mapper
mapper:
  mappers: com.rao.mapper.RainBaseDao
  identity: MYSQL

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# dao 的日志
logging:
  level:
    com:
      rao:
        dao: debug

# 开启断路器
feign:
  hystrix:
    enabled: true
  
  
