spring:
  # 数据源
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/rain_user_dev
    url: jdbc:mysql://localhost:3306/rain_user_dev

  # redis
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 0

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# rocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rain_auth_producer_group
