spring:

  # 数据源
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain_support_dev

  # redis
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 0

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# security
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9000/auth/oauth/token
      user-authorization-uri: http://localhost:9000/auth/oauth/authorize
      grant-type: password,refresh_token
      scope: backend
    resource:
      user-info-uri: http://localhost:9000/auth/user/info
